//! Velkor skills — installable + learned procedural skills.
//!
//! Two types of skills:
//! 1. **Installable**: SKILL.md files (agentskills.io format) placed in a skills
//!    directory. Loaded at startup, names+descriptions in system prompt, full
//!    content loaded on demand via skill_view tool.
//! 2. **Learned**: Auto-generated by the agent after complex tasks, stored in
//!    the database, self-improving via patch operations.

pub mod parser;
pub mod store;
pub mod index;
