/**
 * Generate .env and config.yaml from wizard answers.
 */

import { randomBytes } from "node:crypto";
import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { stringify } from "yaml";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface WizardAnswers {
  // LLM
  llmProvider: string;
  llmApiKey: string;
  llmBaseUrl?: string;
  llmModel?: string;

  // Embeddings
  embeddingProvider: string;
  embeddingApiKey?: string;

  // Search
  searchProvider: string;
  searchApiKey?: string;
  searchModel?: string;

  // Admin
  adminEmail: string;
  adminPassword: string;
}

// ---------------------------------------------------------------------------
// .env generator
// ---------------------------------------------------------------------------

export function generateEnv(
  answers: WizardAnswers,
  projectRoot: string
): string {
  const secret = randomBytes(32).toString("hex");

  const lines: string[] = [
    "# =============================================================================",
    "# Velkor Platform — Generated by velkor setup",
    "# =============================================================================",
    "",
    "# --- Database ----------------------------------------------------------------",
    "POSTGRES_USER=velkor",
    "POSTGRES_PASSWORD=" + randomBytes(16).toString("hex"),
    "POSTGRES_DB=velkor",
    "",
    "# --- Redis -------------------------------------------------------------------",
    "REDIS_URL=redis://redis:6379",
    "",
    "# --- MinIO -------------------------------------------------------------------",
    "MINIO_ROOT_USER=velkor",
    "MINIO_ROOT_PASSWORD=" + randomBytes(16).toString("hex"),
    "S3_ENDPOINT=http://minio:9000",
    "S3_ACCESS_KEY=velkor",
    "S3_SECRET_KEY=" + randomBytes(16).toString("hex"),
    "S3_BUCKET=velkor-documents",
    "",
    "# --- Auth / JWT --------------------------------------------------------------",
    `PLATFORM_SECRET_KEY=${secret}`,
    `JWT_SECRET=${secret}`,
    "",
    "# --- LLM Provider -----------------------------------------------------------",
  ];

  // Set the DATABASE_URL (needs the generated password)
  const pgPass = lines
    .find((l) => l.startsWith("POSTGRES_PASSWORD="))!
    .split("=")[1];
  // Insert DATABASE_URL after POSTGRES_DB
  const dbIdx = lines.findIndex((l) => l.startsWith("POSTGRES_DB="));
  lines.splice(
    dbIdx + 1,
    0,
    `DATABASE_URL=postgresql://velkor:${pgPass}@postgres:5432/velkor`
  );

  // MinIO secret key — sync S3_SECRET_KEY with MINIO_ROOT_PASSWORD
  const minioPass = lines
    .find((l) => l.startsWith("MINIO_ROOT_PASSWORD="))!
    .split("=")[1];
  const s3Idx = lines.findIndex((l) => l.startsWith("S3_SECRET_KEY="));
  lines[s3Idx] = `S3_SECRET_KEY=${minioPass}`;

  // LLM keys
  switch (answers.llmProvider) {
    case "openrouter":
      lines.push(`OPENROUTER_API_KEY=${answers.llmApiKey}`);
      break;
    case "anthropic":
      lines.push(`ANTHROPIC_API_KEY=${answers.llmApiKey}`);
      break;
    case "openai":
      lines.push(`OPENAI_API_KEY=${answers.llmApiKey}`);
      break;
    case "ollama":
      lines.push("# Ollama — no API key needed");
      break;
    case "custom":
      lines.push(`CUSTOM_LLM_API_KEY=${answers.llmApiKey}`);
      break;
  }

  // Embedding keys
  lines.push("");
  lines.push("# --- Embedding Provider -----------------------------------------------------");
  if (answers.embeddingProvider === "openai" && answers.embeddingApiKey) {
    lines.push(`OPENAI_API_KEY=${answers.embeddingApiKey}`);
  }

  // Search keys
  lines.push("");
  lines.push("# --- Search Provider --------------------------------------------------------");
  switch (answers.searchProvider) {
    case "perplexity":
      lines.push(`PERPLEXITY_API_KEY=${answers.searchApiKey ?? ""}`);
      break;
    case "tavily":
      lines.push(`TAVILY_API_KEY=${answers.searchApiKey ?? ""}`);
      break;
    case "brave":
      lines.push(`BRAVE_API_KEY=${answers.searchApiKey ?? ""}`);
      break;
    case "duckduckgo":
      lines.push("# DuckDuckGo — no API key needed");
      break;
    case "skip":
      lines.push("# Search disabled");
      break;
  }

  // Ports
  lines.push("");
  lines.push("# --- Service Ports ----------------------------------------------------------");
  lines.push("CORE_PORT=3001");
  lines.push("API_PORT=3000");
  lines.push("WEB_PORT=8080");
  lines.push("");
  lines.push("CORS_ORIGIN=http://localhost:8080");
  lines.push("");

  const content = lines.join("\n");
  const envPath = resolve(projectRoot, ".env");
  writeFileSync(envPath, content, "utf-8");
  return envPath;
}

// ---------------------------------------------------------------------------
// config.yaml generator
// ---------------------------------------------------------------------------

export function generateConfig(
  answers: WizardAnswers,
  projectRoot: string
): string {
  const config: Record<string, unknown> = {
    platform: {
      name: "Velkor",
      host: "0.0.0.0",
      port: 3001,
      secret_key: "${PLATFORM_SECRET_KEY}",
    },

    database: {
      postgres_url: "${DATABASE_URL}",
      redis_url: "${REDIS_URL}",
      s3: {
        endpoint: "${S3_ENDPOINT}",
        access_key: "${S3_ACCESS_KEY}",
        secret_key: "${S3_SECRET_KEY}",
        bucket: "${S3_BUCKET:-velkor-documents}",
      },
    },
  };

  // Providers
  const providers: Record<string, Record<string, string>> = {};

  switch (answers.llmProvider) {
    case "openrouter":
      providers.openrouter = {
        api_key: "${OPENROUTER_API_KEY}",
        default_model: answers.llmModel || "anthropic/claude-sonnet-4-20250514",
      };
      break;
    case "anthropic":
      providers.anthropic = {
        api_key: "${ANTHROPIC_API_KEY}",
        default_model: answers.llmModel || "claude-sonnet-4-20250514",
      };
      break;
    case "openai":
      providers.openai = {
        api_key: "${OPENAI_API_KEY}",
        default_model: answers.llmModel || "gpt-4o",
      };
      break;
    case "ollama":
      providers.ollama = {
        base_url: answers.llmBaseUrl || "http://host.docker.internal:11434",
        default_model: answers.llmModel || "llama3.1:8b",
      };
      break;
    case "custom":
      providers.custom = {
        api_key: "${CUSTOM_LLM_API_KEY}",
        base_url: answers.llmBaseUrl || "",
        default_model: answers.llmModel || "",
      };
      break;
  }

  // Add embedding provider if it differs from LLM provider
  if (
    answers.embeddingProvider === "openai" &&
    !providers.openai
  ) {
    providers.openai = {
      api_key: "${OPENAI_API_KEY}",
      default_model: "gpt-4o",
    };
  }
  if (answers.embeddingProvider === "ollama" && !providers.ollama) {
    providers.ollama = {
      base_url: "http://host.docker.internal:11434",
      default_model: "llama3.1:8b",
    };
  }

  config.providers = providers;

  // Routing — use the user's selected model as primary in fallback chain
  const fallback: string[] = [];
  if (providers.openrouter)
    fallback.push(answers.llmModel || "anthropic/claude-sonnet-4-20250514");
  if (providers.anthropic)
    fallback.push(answers.llmModel || "claude-sonnet-4-20250514");
  if (providers.openai) fallback.push(answers.llmModel || "gpt-4o");
  if (providers.ollama)
    fallback.push(`ollama/${answers.llmModel || "llama3.1:8b"}`);
  if (providers.custom && answers.llmModel)
    fallback.push(answers.llmModel);

  config.routing = {
    strategy: "cost_optimized",
    fallback_chain: fallback,
    cost_limit_daily_usd: 10.0,
    cost_limit_monthly_usd: 200.0,
  };

  // Memory / embeddings
  let embeddingModel = "openai/text-embedding-3-small";
  let embeddingDims = 1536;

  if (answers.embeddingProvider === "ollama") {
    embeddingModel = "ollama/nomic-embed-text";
    embeddingDims = 768;
  } else if (answers.embeddingProvider === "skip") {
    embeddingModel = "none";
    embeddingDims = 0;
  }

  config.memory = {
    embedding_model: embeddingModel,
    embedding_dimensions: embeddingDims,
    auto_memorize: true,
    user_modeling: true,
    context_compression: {
      strategy: "summarize",
      max_context_tokens: 100000,
    },
  };

  // Tools / web search
  const toolsSearch: Record<string, unknown> = {
    provider: answers.searchProvider === "skip" ? "none" : answers.searchProvider,
    max_results: 5,
  };

  switch (answers.searchProvider) {
    case "tavily":
      toolsSearch.tavily_api_key = "${TAVILY_API_KEY:-}";
      break;
    case "brave":
      toolsSearch.brave_api_key = "${BRAVE_API_KEY:-}";
      break;
    case "perplexity":
      toolsSearch.perplexity = {
        api_key: "${PERPLEXITY_API_KEY:-}",
        model: answers.searchModel || "sonar-pro",
      };
      break;
  }

  config.tools = {
    web_search: toolsSearch,
    web_fetch: { enabled: true, max_content_length: 50000 },
  };

  // Scheduling, retention, channels
  config.scheduling = {
    enabled: true,
    heartbeat_interval_seconds: 60,
    timezone: "UTC",
  };

  config.retention = {
    default_conversation_days: 365,
    default_memory_days: null,
    default_document_days: null,
    audit_log_days: 2555,
    auto_purge: true,
    purge_schedule: "0 2 * * *",
  };

  config.channels = {
    web: { enabled: true },
    api: { enabled: true, rate_limit_per_minute: 100 },
  };

  const yamlStr = stringify(config, { lineWidth: 120 });
  const configPath = resolve(projectRoot, "config.docker.yaml");
  writeFileSync(configPath, yamlStr, "utf-8");
  return configPath;
}

// ---------------------------------------------------------------------------
// Check if .env already exists
// ---------------------------------------------------------------------------

export function envExists(projectRoot: string): boolean {
  return existsSync(resolve(projectRoot, ".env"));
}
